name: DonBenny
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  provider: ^4.3.1
  flutter_svg: ^0.18.0
  transparent_image: ^1.0.0
  cached_network_image: ^2.3.3
  carousel_slider: ^2.3.1
  built_value: ^7.1.0
  built_collection: ^4.3.2
  dio: ^3.0.10
  jaguar_jwt: ^2.1.6

  http: ^0.12.2
  shared_preferences: ^0.5.12+2
  sqflite: ^1.3.1+2
  path_provider: ^1.6.21
  intl: ^0.16.1

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  logger: ^0.8.3
  build_runner: ^1.7.1
  built_value_generator: ^7.0.4 

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Muli
      fonts:
        - asset: assets\fonts\muli\Muli.ttf
        - asset: assets\fonts\muli\Muli-Bold.ttf
          weight: 700
        - asset: assets\fonts\muli\Muli-Light.ttf
          weight: 300
